// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemTapMessage.proto

package com.systemtap.android.net;

public final class SystemTapMessage {
  private SystemTapMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code SystemTapMessage.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ACK = 1;</code>
     */
    ACK(0, 1),
    /**
     * <code>SEND_MODULE = 2;</code>
     */
    SEND_MODULE(1, 2),
    /**
     * <code>LIST_MODULES = 3;</code>
     */
    LIST_MODULES(2, 3),
    /**
     * <code>MODULE_LIST = 4;</code>
     */
    MODULE_LIST(3, 4),
    /**
     * <code>CONTROL_MODULE = 5;</code>
     */
    CONTROL_MODULE(4, 5),
    ;

    /**
     * <code>ACK = 1;</code>
     */
    public static final int ACK_VALUE = 1;
    /**
     * <code>SEND_MODULE = 2;</code>
     */
    public static final int SEND_MODULE_VALUE = 2;
    /**
     * <code>LIST_MODULES = 3;</code>
     */
    public static final int LIST_MODULES_VALUE = 3;
    /**
     * <code>MODULE_LIST = 4;</code>
     */
    public static final int MODULE_LIST_VALUE = 4;
    /**
     * <code>CONTROL_MODULE = 5;</code>
     */
    public static final int CONTROL_MODULE_VALUE = 5;


    public final int getNumber() { return value; }

    public static MessageType valueOf(int value) {
      switch (value) {
        case 1: return ACK;
        case 2: return SEND_MODULE;
        case 3: return LIST_MODULES;
        case 4: return MODULE_LIST;
        case 5: return CONTROL_MODULE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.systemtap.android.net.SystemTapMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SystemTapMessage.MessageType)
  }

  /**
   * Protobuf enum {@code SystemTapMessage.ModuleStatus}
   */
  public enum ModuleStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RUNNING = 0;</code>
     */
    RUNNING(0, 0),
    /**
     * <code>STOPPED = 1;</code>
     */
    STOPPED(1, 1),
    /**
     * <code>CRASHED = 2;</code>
     */
    CRASHED(2, 2),
    /**
     * <code>DELETED = 3;</code>
     */
    DELETED(3, 3),
    ;

    /**
     * <code>RUNNING = 0;</code>
     */
    public static final int RUNNING_VALUE = 0;
    /**
     * <code>STOPPED = 1;</code>
     */
    public static final int STOPPED_VALUE = 1;
    /**
     * <code>CRASHED = 2;</code>
     */
    public static final int CRASHED_VALUE = 2;
    /**
     * <code>DELETED = 3;</code>
     */
    public static final int DELETED_VALUE = 3;


    public final int getNumber() { return value; }

    public static ModuleStatus valueOf(int value) {
      switch (value) {
        case 0: return RUNNING;
        case 1: return STOPPED;
        case 2: return CRASHED;
        case 3: return DELETED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ModuleStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ModuleStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ModuleStatus>() {
            public ModuleStatus findValueByNumber(int number) {
              return ModuleStatus.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.systemtap.android.net.SystemTapMessage.getDescriptor().getEnumTypes().get(1);
    }

    private static final ModuleStatus[] VALUES = values();

    public static ModuleStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ModuleStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SystemTapMessage.ModuleStatus)
  }

  public interface SendModuleOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required bytes data = 2;
    /**
     * <code>required bytes data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>required bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code SystemTapMessage.SendModule}
   */
  public static final class SendModule extends
      com.google.protobuf.GeneratedMessage
      implements SendModuleOrBuilder {
    // Use SendModule.newBuilder() to construct.
    private SendModule(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SendModule(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SendModule defaultInstance;
    public static SendModule getDefaultInstance() {
      return defaultInstance;
    }

    public SendModule getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SendModule(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_SendModule_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_SendModule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.systemtap.android.net.SystemTapMessage.SendModule.class, com.systemtap.android.net.SystemTapMessage.SendModule.Builder.class);
    }

    public static com.google.protobuf.Parser<SendModule> PARSER =
        new com.google.protobuf.AbstractParser<SendModule>() {
      public SendModule parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendModule(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SendModule> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bytes data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      name_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.systemtap.android.net.SystemTapMessage.SendModule parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.systemtap.android.net.SystemTapMessage.SendModule parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.systemtap.android.net.SystemTapMessage.SendModule parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.systemtap.android.net.SystemTapMessage.SendModule parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.systemtap.android.net.SystemTapMessage.SendModule parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.systemtap.android.net.SystemTapMessage.SendModule parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.systemtap.android.net.SystemTapMessage.SendModule parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.systemtap.android.net.SystemTapMessage.SendModule parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.systemtap.android.net.SystemTapMessage.SendModule parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.systemtap.android.net.SystemTapMessage.SendModule parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.systemtap.android.net.SystemTapMessage.SendModule prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SystemTapMessage.SendModule}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.systemtap.android.net.SystemTapMessage.SendModuleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_SendModule_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_SendModule_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.systemtap.android.net.SystemTapMessage.SendModule.class, com.systemtap.android.net.SystemTapMessage.SendModule.Builder.class);
      }

      // Construct using com.systemtap.android.net.SystemTapMessage.SendModule.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_SendModule_descriptor;
      }

      public com.systemtap.android.net.SystemTapMessage.SendModule getDefaultInstanceForType() {
        return com.systemtap.android.net.SystemTapMessage.SendModule.getDefaultInstance();
      }

      public com.systemtap.android.net.SystemTapMessage.SendModule build() {
        com.systemtap.android.net.SystemTapMessage.SendModule result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.systemtap.android.net.SystemTapMessage.SendModule buildPartial() {
        com.systemtap.android.net.SystemTapMessage.SendModule result = new com.systemtap.android.net.SystemTapMessage.SendModule(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.systemtap.android.net.SystemTapMessage.SendModule) {
          return mergeFrom((com.systemtap.android.net.SystemTapMessage.SendModule)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.systemtap.android.net.SystemTapMessage.SendModule other) {
        if (other == com.systemtap.android.net.SystemTapMessage.SendModule.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.systemtap.android.net.SystemTapMessage.SendModule parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.systemtap.android.net.SystemTapMessage.SendModule) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // required bytes data = 2;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SystemTapMessage.SendModule)
    }

    static {
      defaultInstance = new SendModule(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SystemTapMessage.SendModule)
  }

  public interface ModuleInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required .SystemTapMessage.ModuleStatus status = 2;
    /**
     * <code>required .SystemTapMessage.ModuleStatus status = 2;</code>
     */
    boolean hasStatus();
    /**
     * <code>required .SystemTapMessage.ModuleStatus status = 2;</code>
     */
    com.systemtap.android.net.SystemTapMessage.ModuleStatus getStatus();
  }
  /**
   * Protobuf type {@code SystemTapMessage.ModuleInfo}
   */
  public static final class ModuleInfo extends
      com.google.protobuf.GeneratedMessage
      implements ModuleInfoOrBuilder {
    // Use ModuleInfo.newBuilder() to construct.
    private ModuleInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ModuleInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ModuleInfo defaultInstance;
    public static ModuleInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ModuleInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ModuleInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.systemtap.android.net.SystemTapMessage.ModuleStatus value = com.systemtap.android.net.SystemTapMessage.ModuleStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                status_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_ModuleInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_ModuleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.systemtap.android.net.SystemTapMessage.ModuleInfo.class, com.systemtap.android.net.SystemTapMessage.ModuleInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ModuleInfo> PARSER =
        new com.google.protobuf.AbstractParser<ModuleInfo>() {
      public ModuleInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ModuleInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ModuleInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .SystemTapMessage.ModuleStatus status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private com.systemtap.android.net.SystemTapMessage.ModuleStatus status_;
    /**
     * <code>required .SystemTapMessage.ModuleStatus status = 2;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .SystemTapMessage.ModuleStatus status = 2;</code>
     */
    public com.systemtap.android.net.SystemTapMessage.ModuleStatus getStatus() {
      return status_;
    }

    private void initFields() {
      name_ = "";
      status_ = com.systemtap.android.net.SystemTapMessage.ModuleStatus.RUNNING;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, status_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.systemtap.android.net.SystemTapMessage.ModuleInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.systemtap.android.net.SystemTapMessage.ModuleInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.systemtap.android.net.SystemTapMessage.ModuleInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.systemtap.android.net.SystemTapMessage.ModuleInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.systemtap.android.net.SystemTapMessage.ModuleInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.systemtap.android.net.SystemTapMessage.ModuleInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.systemtap.android.net.SystemTapMessage.ModuleInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.systemtap.android.net.SystemTapMessage.ModuleInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.systemtap.android.net.SystemTapMessage.ModuleInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.systemtap.android.net.SystemTapMessage.ModuleInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.systemtap.android.net.SystemTapMessage.ModuleInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SystemTapMessage.ModuleInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.systemtap.android.net.SystemTapMessage.ModuleInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_ModuleInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_ModuleInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.systemtap.android.net.SystemTapMessage.ModuleInfo.class, com.systemtap.android.net.SystemTapMessage.ModuleInfo.Builder.class);
      }

      // Construct using com.systemtap.android.net.SystemTapMessage.ModuleInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = com.systemtap.android.net.SystemTapMessage.ModuleStatus.RUNNING;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_ModuleInfo_descriptor;
      }

      public com.systemtap.android.net.SystemTapMessage.ModuleInfo getDefaultInstanceForType() {
        return com.systemtap.android.net.SystemTapMessage.ModuleInfo.getDefaultInstance();
      }

      public com.systemtap.android.net.SystemTapMessage.ModuleInfo build() {
        com.systemtap.android.net.SystemTapMessage.ModuleInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.systemtap.android.net.SystemTapMessage.ModuleInfo buildPartial() {
        com.systemtap.android.net.SystemTapMessage.ModuleInfo result = new com.systemtap.android.net.SystemTapMessage.ModuleInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.systemtap.android.net.SystemTapMessage.ModuleInfo) {
          return mergeFrom((com.systemtap.android.net.SystemTapMessage.ModuleInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.systemtap.android.net.SystemTapMessage.ModuleInfo other) {
        if (other == com.systemtap.android.net.SystemTapMessage.ModuleInfo.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.systemtap.android.net.SystemTapMessage.ModuleInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.systemtap.android.net.SystemTapMessage.ModuleInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // required .SystemTapMessage.ModuleStatus status = 2;
      private com.systemtap.android.net.SystemTapMessage.ModuleStatus status_ = com.systemtap.android.net.SystemTapMessage.ModuleStatus.RUNNING;
      /**
       * <code>required .SystemTapMessage.ModuleStatus status = 2;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .SystemTapMessage.ModuleStatus status = 2;</code>
       */
      public com.systemtap.android.net.SystemTapMessage.ModuleStatus getStatus() {
        return status_;
      }
      /**
       * <code>required .SystemTapMessage.ModuleStatus status = 2;</code>
       */
      public Builder setStatus(com.systemtap.android.net.SystemTapMessage.ModuleStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .SystemTapMessage.ModuleStatus status = 2;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = com.systemtap.android.net.SystemTapMessage.ModuleStatus.RUNNING;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SystemTapMessage.ModuleInfo)
    }

    static {
      defaultInstance = new ModuleInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SystemTapMessage.ModuleInfo)
  }

  public interface ModuleListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .SystemTapMessage.ModuleInfo modules = 1;
    /**
     * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
     */
    java.util.List<com.systemtap.android.net.SystemTapMessage.ModuleInfo> 
        getModulesList();
    /**
     * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
     */
    com.systemtap.android.net.SystemTapMessage.ModuleInfo getModules(int index);
    /**
     * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
     */
    int getModulesCount();
    /**
     * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
     */
    java.util.List<? extends com.systemtap.android.net.SystemTapMessage.ModuleInfoOrBuilder> 
        getModulesOrBuilderList();
    /**
     * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
     */
    com.systemtap.android.net.SystemTapMessage.ModuleInfoOrBuilder getModulesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code SystemTapMessage.ModuleList}
   */
  public static final class ModuleList extends
      com.google.protobuf.GeneratedMessage
      implements ModuleListOrBuilder {
    // Use ModuleList.newBuilder() to construct.
    private ModuleList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ModuleList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ModuleList defaultInstance;
    public static ModuleList getDefaultInstance() {
      return defaultInstance;
    }

    public ModuleList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ModuleList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                modules_ = new java.util.ArrayList<com.systemtap.android.net.SystemTapMessage.ModuleInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              modules_.add(input.readMessage(com.systemtap.android.net.SystemTapMessage.ModuleInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          modules_ = java.util.Collections.unmodifiableList(modules_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_ModuleList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_ModuleList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.systemtap.android.net.SystemTapMessage.ModuleList.class, com.systemtap.android.net.SystemTapMessage.ModuleList.Builder.class);
    }

    public static com.google.protobuf.Parser<ModuleList> PARSER =
        new com.google.protobuf.AbstractParser<ModuleList>() {
      public ModuleList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ModuleList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ModuleList> getParserForType() {
      return PARSER;
    }

    // repeated .SystemTapMessage.ModuleInfo modules = 1;
    public static final int MODULES_FIELD_NUMBER = 1;
    private java.util.List<com.systemtap.android.net.SystemTapMessage.ModuleInfo> modules_;
    /**
     * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
     */
    public java.util.List<com.systemtap.android.net.SystemTapMessage.ModuleInfo> getModulesList() {
      return modules_;
    }
    /**
     * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
     */
    public java.util.List<? extends com.systemtap.android.net.SystemTapMessage.ModuleInfoOrBuilder> 
        getModulesOrBuilderList() {
      return modules_;
    }
    /**
     * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
     */
    public int getModulesCount() {
      return modules_.size();
    }
    /**
     * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
     */
    public com.systemtap.android.net.SystemTapMessage.ModuleInfo getModules(int index) {
      return modules_.get(index);
    }
    /**
     * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
     */
    public com.systemtap.android.net.SystemTapMessage.ModuleInfoOrBuilder getModulesOrBuilder(
        int index) {
      return modules_.get(index);
    }

    private void initFields() {
      modules_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getModulesCount(); i++) {
        if (!getModules(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < modules_.size(); i++) {
        output.writeMessage(1, modules_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < modules_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, modules_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.systemtap.android.net.SystemTapMessage.ModuleList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.systemtap.android.net.SystemTapMessage.ModuleList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.systemtap.android.net.SystemTapMessage.ModuleList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.systemtap.android.net.SystemTapMessage.ModuleList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.systemtap.android.net.SystemTapMessage.ModuleList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.systemtap.android.net.SystemTapMessage.ModuleList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.systemtap.android.net.SystemTapMessage.ModuleList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.systemtap.android.net.SystemTapMessage.ModuleList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.systemtap.android.net.SystemTapMessage.ModuleList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.systemtap.android.net.SystemTapMessage.ModuleList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.systemtap.android.net.SystemTapMessage.ModuleList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SystemTapMessage.ModuleList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.systemtap.android.net.SystemTapMessage.ModuleListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_ModuleList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_ModuleList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.systemtap.android.net.SystemTapMessage.ModuleList.class, com.systemtap.android.net.SystemTapMessage.ModuleList.Builder.class);
      }

      // Construct using com.systemtap.android.net.SystemTapMessage.ModuleList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getModulesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (modulesBuilder_ == null) {
          modules_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          modulesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_ModuleList_descriptor;
      }

      public com.systemtap.android.net.SystemTapMessage.ModuleList getDefaultInstanceForType() {
        return com.systemtap.android.net.SystemTapMessage.ModuleList.getDefaultInstance();
      }

      public com.systemtap.android.net.SystemTapMessage.ModuleList build() {
        com.systemtap.android.net.SystemTapMessage.ModuleList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.systemtap.android.net.SystemTapMessage.ModuleList buildPartial() {
        com.systemtap.android.net.SystemTapMessage.ModuleList result = new com.systemtap.android.net.SystemTapMessage.ModuleList(this);
        int from_bitField0_ = bitField0_;
        if (modulesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            modules_ = java.util.Collections.unmodifiableList(modules_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.modules_ = modules_;
        } else {
          result.modules_ = modulesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.systemtap.android.net.SystemTapMessage.ModuleList) {
          return mergeFrom((com.systemtap.android.net.SystemTapMessage.ModuleList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.systemtap.android.net.SystemTapMessage.ModuleList other) {
        if (other == com.systemtap.android.net.SystemTapMessage.ModuleList.getDefaultInstance()) return this;
        if (modulesBuilder_ == null) {
          if (!other.modules_.isEmpty()) {
            if (modules_.isEmpty()) {
              modules_ = other.modules_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureModulesIsMutable();
              modules_.addAll(other.modules_);
            }
            onChanged();
          }
        } else {
          if (!other.modules_.isEmpty()) {
            if (modulesBuilder_.isEmpty()) {
              modulesBuilder_.dispose();
              modulesBuilder_ = null;
              modules_ = other.modules_;
              bitField0_ = (bitField0_ & ~0x00000001);
              modulesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getModulesFieldBuilder() : null;
            } else {
              modulesBuilder_.addAllMessages(other.modules_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getModulesCount(); i++) {
          if (!getModules(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.systemtap.android.net.SystemTapMessage.ModuleList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.systemtap.android.net.SystemTapMessage.ModuleList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .SystemTapMessage.ModuleInfo modules = 1;
      private java.util.List<com.systemtap.android.net.SystemTapMessage.ModuleInfo> modules_ =
        java.util.Collections.emptyList();
      private void ensureModulesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          modules_ = new java.util.ArrayList<com.systemtap.android.net.SystemTapMessage.ModuleInfo>(modules_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.systemtap.android.net.SystemTapMessage.ModuleInfo, com.systemtap.android.net.SystemTapMessage.ModuleInfo.Builder, com.systemtap.android.net.SystemTapMessage.ModuleInfoOrBuilder> modulesBuilder_;

      /**
       * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
       */
      public java.util.List<com.systemtap.android.net.SystemTapMessage.ModuleInfo> getModulesList() {
        if (modulesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(modules_);
        } else {
          return modulesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
       */
      public int getModulesCount() {
        if (modulesBuilder_ == null) {
          return modules_.size();
        } else {
          return modulesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
       */
      public com.systemtap.android.net.SystemTapMessage.ModuleInfo getModules(int index) {
        if (modulesBuilder_ == null) {
          return modules_.get(index);
        } else {
          return modulesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
       */
      public Builder setModules(
          int index, com.systemtap.android.net.SystemTapMessage.ModuleInfo value) {
        if (modulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureModulesIsMutable();
          modules_.set(index, value);
          onChanged();
        } else {
          modulesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
       */
      public Builder setModules(
          int index, com.systemtap.android.net.SystemTapMessage.ModuleInfo.Builder builderForValue) {
        if (modulesBuilder_ == null) {
          ensureModulesIsMutable();
          modules_.set(index, builderForValue.build());
          onChanged();
        } else {
          modulesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
       */
      public Builder addModules(com.systemtap.android.net.SystemTapMessage.ModuleInfo value) {
        if (modulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureModulesIsMutable();
          modules_.add(value);
          onChanged();
        } else {
          modulesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
       */
      public Builder addModules(
          int index, com.systemtap.android.net.SystemTapMessage.ModuleInfo value) {
        if (modulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureModulesIsMutable();
          modules_.add(index, value);
          onChanged();
        } else {
          modulesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
       */
      public Builder addModules(
          com.systemtap.android.net.SystemTapMessage.ModuleInfo.Builder builderForValue) {
        if (modulesBuilder_ == null) {
          ensureModulesIsMutable();
          modules_.add(builderForValue.build());
          onChanged();
        } else {
          modulesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
       */
      public Builder addModules(
          int index, com.systemtap.android.net.SystemTapMessage.ModuleInfo.Builder builderForValue) {
        if (modulesBuilder_ == null) {
          ensureModulesIsMutable();
          modules_.add(index, builderForValue.build());
          onChanged();
        } else {
          modulesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
       */
      public Builder addAllModules(
          java.lang.Iterable<? extends com.systemtap.android.net.SystemTapMessage.ModuleInfo> values) {
        if (modulesBuilder_ == null) {
          ensureModulesIsMutable();
          super.addAll(values, modules_);
          onChanged();
        } else {
          modulesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
       */
      public Builder clearModules() {
        if (modulesBuilder_ == null) {
          modules_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          modulesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
       */
      public Builder removeModules(int index) {
        if (modulesBuilder_ == null) {
          ensureModulesIsMutable();
          modules_.remove(index);
          onChanged();
        } else {
          modulesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
       */
      public com.systemtap.android.net.SystemTapMessage.ModuleInfo.Builder getModulesBuilder(
          int index) {
        return getModulesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
       */
      public com.systemtap.android.net.SystemTapMessage.ModuleInfoOrBuilder getModulesOrBuilder(
          int index) {
        if (modulesBuilder_ == null) {
          return modules_.get(index);  } else {
          return modulesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
       */
      public java.util.List<? extends com.systemtap.android.net.SystemTapMessage.ModuleInfoOrBuilder> 
           getModulesOrBuilderList() {
        if (modulesBuilder_ != null) {
          return modulesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(modules_);
        }
      }
      /**
       * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
       */
      public com.systemtap.android.net.SystemTapMessage.ModuleInfo.Builder addModulesBuilder() {
        return getModulesFieldBuilder().addBuilder(
            com.systemtap.android.net.SystemTapMessage.ModuleInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
       */
      public com.systemtap.android.net.SystemTapMessage.ModuleInfo.Builder addModulesBuilder(
          int index) {
        return getModulesFieldBuilder().addBuilder(
            index, com.systemtap.android.net.SystemTapMessage.ModuleInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .SystemTapMessage.ModuleInfo modules = 1;</code>
       */
      public java.util.List<com.systemtap.android.net.SystemTapMessage.ModuleInfo.Builder> 
           getModulesBuilderList() {
        return getModulesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.systemtap.android.net.SystemTapMessage.ModuleInfo, com.systemtap.android.net.SystemTapMessage.ModuleInfo.Builder, com.systemtap.android.net.SystemTapMessage.ModuleInfoOrBuilder> 
          getModulesFieldBuilder() {
        if (modulesBuilder_ == null) {
          modulesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.systemtap.android.net.SystemTapMessage.ModuleInfo, com.systemtap.android.net.SystemTapMessage.ModuleInfo.Builder, com.systemtap.android.net.SystemTapMessage.ModuleInfoOrBuilder>(
                  modules_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          modules_ = null;
        }
        return modulesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:SystemTapMessage.ModuleList)
    }

    static {
      defaultInstance = new ModuleList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SystemTapMessage.ModuleList)
  }

  public interface AckOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 ackedType = 1;
    /**
     * <code>required int32 ackedType = 1;</code>
     */
    boolean hasAckedType();
    /**
     * <code>required int32 ackedType = 1;</code>
     */
    int getAckedType();
  }
  /**
   * Protobuf type {@code SystemTapMessage.Ack}
   */
  public static final class Ack extends
      com.google.protobuf.GeneratedMessage
      implements AckOrBuilder {
    // Use Ack.newBuilder() to construct.
    private Ack(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Ack(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Ack defaultInstance;
    public static Ack getDefaultInstance() {
      return defaultInstance;
    }

    public Ack getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Ack(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ackedType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_Ack_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_Ack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.systemtap.android.net.SystemTapMessage.Ack.class, com.systemtap.android.net.SystemTapMessage.Ack.Builder.class);
    }

    public static com.google.protobuf.Parser<Ack> PARSER =
        new com.google.protobuf.AbstractParser<Ack>() {
      public Ack parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Ack(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Ack> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 ackedType = 1;
    public static final int ACKEDTYPE_FIELD_NUMBER = 1;
    private int ackedType_;
    /**
     * <code>required int32 ackedType = 1;</code>
     */
    public boolean hasAckedType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 ackedType = 1;</code>
     */
    public int getAckedType() {
      return ackedType_;
    }

    private void initFields() {
      ackedType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAckedType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, ackedType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ackedType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.systemtap.android.net.SystemTapMessage.Ack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.systemtap.android.net.SystemTapMessage.Ack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.systemtap.android.net.SystemTapMessage.Ack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.systemtap.android.net.SystemTapMessage.Ack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.systemtap.android.net.SystemTapMessage.Ack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.systemtap.android.net.SystemTapMessage.Ack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.systemtap.android.net.SystemTapMessage.Ack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.systemtap.android.net.SystemTapMessage.Ack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.systemtap.android.net.SystemTapMessage.Ack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.systemtap.android.net.SystemTapMessage.Ack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.systemtap.android.net.SystemTapMessage.Ack prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SystemTapMessage.Ack}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.systemtap.android.net.SystemTapMessage.AckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_Ack_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_Ack_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.systemtap.android.net.SystemTapMessage.Ack.class, com.systemtap.android.net.SystemTapMessage.Ack.Builder.class);
      }

      // Construct using com.systemtap.android.net.SystemTapMessage.Ack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ackedType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.systemtap.android.net.SystemTapMessage.internal_static_SystemTapMessage_Ack_descriptor;
      }

      public com.systemtap.android.net.SystemTapMessage.Ack getDefaultInstanceForType() {
        return com.systemtap.android.net.SystemTapMessage.Ack.getDefaultInstance();
      }

      public com.systemtap.android.net.SystemTapMessage.Ack build() {
        com.systemtap.android.net.SystemTapMessage.Ack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.systemtap.android.net.SystemTapMessage.Ack buildPartial() {
        com.systemtap.android.net.SystemTapMessage.Ack result = new com.systemtap.android.net.SystemTapMessage.Ack(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ackedType_ = ackedType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.systemtap.android.net.SystemTapMessage.Ack) {
          return mergeFrom((com.systemtap.android.net.SystemTapMessage.Ack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.systemtap.android.net.SystemTapMessage.Ack other) {
        if (other == com.systemtap.android.net.SystemTapMessage.Ack.getDefaultInstance()) return this;
        if (other.hasAckedType()) {
          setAckedType(other.getAckedType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAckedType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.systemtap.android.net.SystemTapMessage.Ack parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.systemtap.android.net.SystemTapMessage.Ack) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 ackedType = 1;
      private int ackedType_ ;
      /**
       * <code>required int32 ackedType = 1;</code>
       */
      public boolean hasAckedType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 ackedType = 1;</code>
       */
      public int getAckedType() {
        return ackedType_;
      }
      /**
       * <code>required int32 ackedType = 1;</code>
       */
      public Builder setAckedType(int value) {
        bitField0_ |= 0x00000001;
        ackedType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ackedType = 1;</code>
       */
      public Builder clearAckedType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ackedType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SystemTapMessage.Ack)
    }

    static {
      defaultInstance = new Ack(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SystemTapMessage.Ack)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SystemTapMessage_SendModule_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SystemTapMessage_SendModule_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SystemTapMessage_ModuleInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SystemTapMessage_ModuleInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SystemTapMessage_ModuleList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SystemTapMessage_ModuleList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SystemTapMessage_Ack_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SystemTapMessage_Ack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026SystemTapMessage.proto\022\020SystemTapMessa" +
      "ge\"(\n\nSendModule\022\014\n\004name\030\001 \002(\t\022\014\n\004data\030\002" +
      " \002(\014\"J\n\nModuleInfo\022\014\n\004name\030\001 \002(\t\022.\n\006stat" +
      "us\030\002 \002(\0162\036.SystemTapMessage.ModuleStatus" +
      "\";\n\nModuleList\022-\n\007modules\030\001 \003(\0132\034.System" +
      "TapMessage.ModuleInfo\"\030\n\003Ack\022\021\n\tackedTyp" +
      "e\030\001 \002(\005*^\n\013MessageType\022\007\n\003ACK\020\001\022\017\n\013SEND_" +
      "MODULE\020\002\022\020\n\014LIST_MODULES\020\003\022\017\n\013MODULE_LIS" +
      "T\020\004\022\022\n\016CONTROL_MODULE\020\005*B\n\014ModuleStatus\022" +
      "\013\n\007RUNNING\020\000\022\013\n\007STOPPED\020\001\022\013\n\007CRASHED\020\002\022\013",
      "\n\007DELETED\020\003B\033\n\031com.systemtap.android.net"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SystemTapMessage_SendModule_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SystemTapMessage_SendModule_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SystemTapMessage_SendModule_descriptor,
              new java.lang.String[] { "Name", "Data", });
          internal_static_SystemTapMessage_ModuleInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_SystemTapMessage_ModuleInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SystemTapMessage_ModuleInfo_descriptor,
              new java.lang.String[] { "Name", "Status", });
          internal_static_SystemTapMessage_ModuleList_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_SystemTapMessage_ModuleList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SystemTapMessage_ModuleList_descriptor,
              new java.lang.String[] { "Modules", });
          internal_static_SystemTapMessage_Ack_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_SystemTapMessage_Ack_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SystemTapMessage_Ack_descriptor,
              new java.lang.String[] { "AckedType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
